### ISSUE TITLE
Heading command is applied to too many blocks

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-heading#9]
Not sure is it format plugin on engine bug.
1. open classic editor sample (http://tests.ckeditor.dev:1030/build/amd/tests/creator-classic/manual/classic),
2. triple-click on the heading to select the whole header,
3. change the format.

Result: the paragraph after the header is converted into a heading too.

Expected: only the heading which was triple clicked should be affected.

![format-bug](https://cloud.githubusercontent.com/assets/1166967/16037534/3dbd7a9a-3221-11e6-8e6e-3efb63c68531.gif)

**Comment by scofalik** [comment]
I'm guessing that the model selection somehow ends up in the paragraph. Or is enlarged and then ends up in the paragraph.

**Comment by Reinmar** [comment]
Quoting myself:

> Stupid triple-clicks.
>
> That's not a bug nowhere near formats I’m afraid
>
> Triple click yields you a selection which ends in the next block.

**Comment by pjasiun** [comment]
Same when I select header dragging down:

![format-bug2](https://cloud.githubusercontent.com/assets/1166967/16037865/b7dc94f4-3222-11e6-8766-5bc943ce05bf.gif)

**Comment by pjasiun** [comment]
And I am really do not do it on purpose. This is how I used to select header.

**Comment by scofalik** [comment]
I think that such selection should be fixed. Maybe it could be done together with fixing selection that ends up in graveyard?

**Comment by Reinmar** [comment]
This is really tricky. It's not only about formats, but also e.g. about blockquote, so a general solution needs to be found.

The main issue here is that the selection really spans over 2 elements. It's just not rendered correctly – you don't see that a block ending was selected (other browsers may display such selections more clearly).

So we have to find a solution carefully. E.g. we may consider converting such a selection from view to model differently so it's contained in one block if a specific browser displays it like this in the view. But then we may bring something on the loop back – during rendering. So it just needs to be researched.

**Comment by fredck** [comment]
This has been dealt with success in CKEditor 4, so it may be worth checking what kind of normalization is done there.

**Comment by Reinmar** [comment]
I can reproduce the same issue in CKE4. And I remember reports about this. Either it got broken at some point or it wasn't fully fixed or it wasn't fixed at all (due to some different issues). I think it was the last option, because I don't remember anything in the code about this issue.

**Comment by pjasiun** [comment]
We could introduce `model.selection.getBlocks()` method which will return elements which should be used by features like format or blockquote.

**Comment by pjasiun** [comment]
I mean fixing selection would be nice, but might be more expensive in terms of changes we would have to do.

**Comment by scofalik** [comment]
Dup: https://github.com/ckeditor/ckeditor5/issues/315

BTW. I see now that you discussed `getBlocks()` method. This is a method that I right now prototyped in List feature. We should have a discussion how it should work because it is nowhere being trivial.

**Comment by Reinmar** [comment]
I came to the same conclusions in https://github.com/ckeditor/ckeditor5-ui/issues/180#issuecomment-306056532 independently (I completely forgot the ideas proposed here) so I guess we're all fine.

What I'd do here is the minimal fix which is *only* about ignoring the ending block. That's because selections like this

```html
<paragraph>[</paragraph>
<paragraph>]xx</paragraph>
```

have high chance to be created by triple click in that first empty paragraph. Of course, we cannot exclude that possibility that the user intentionally started selection in the second paragraph but even Google Docs fails on that. But it doesn't even need to be a bug – it's how things are.

![jun-04-2017 20-13-01](https://cloud.githubusercontent.com/assets/156149/26764182/89423f7e-4962-11e7-9a4c-5b9b6c2d26df.gif)

PS. This must be explained in the docs with a proper rationale.

**Comment by Reinmar** [comment]
It will be fixed in https://github.com/ckeditor/ckeditor5-heading/issues/82.

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-engine/issues/984.
